name: New issue with New Assignee
on:
  issues:
    types: [opened]
permissions:
  issues: write  # Explicitly grants write permission to manage issues
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new assignee
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
